plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexa.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.nexa.demo"
        minSdk 24
        targetSdk 34
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    packaging {
        jniLibs.useLegacyPackaging = true
    }
}

dependencies {
    implementation files('libs/nexa-core.aar')
}
