plugins {
    id 'com.android.application' version '7.4.2' apply false
}

apply plugin: 'com.android.application'

android {
    namespace 'com.nexa.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.nexa.demo"
        minSdk 24
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    packaging {
        jniLibs.useLegacyPackaging = true
    }
}

dependencies {
    implementation 'ai.nexa:core:0.0.22'
}
